### ISSUE TITLE
[BUG] TextCNN训练速度很慢

### ISSUE THREAD

**Issue by wfnian** [649453932/Chinese-Text-Classification-Pytorch#115]

**Comment by hxj2580** [comment]
知道为啥了吗，我也遇到这个问题

**Comment by wfnian** [comment]
> 知道为啥了吗，我也遇到这个问题

最后也没有解决。你按照作者的环境要求试试？我当时在自己电脑和autodl平台试了都比较慢。你要不再试试autodl平台上是不是还是很慢？

**Comment by hxj2580** [comment]
> > 知道为啥了吗，我也遇到这个问题
> 
> 最后也没有解决。你按照作者的环境要求试试？我当时在自己电脑和autodl平台试了都比较慢。你要不再试试autodl平台上是不是还是很慢？

我在autodl上试的快一个小时了，一个epoch都没跑完，这全跑完得多久啊，什么原因清楚吗？

**Comment by wfnian** [comment]
> > > 知道为啥了吗，我也遇到这个问题
> > 
> > 
> > 最后也没有解决。你按照作者的环境要求试试？我当时在自己电脑和autodl平台试了都比较慢。你要不再试试autodl平台上是不是还是很慢？
> 
> 我在autodl上试的快一个小时了，一个epoch都没跑完，这全跑完得多久啊，什么原因清楚吗？

那估计这个代码不兼容新版本torch吧。我当时放弃使用了。
