### ISSUE TITLE
utils.py中的def __next__(self)好像有一点小问题

### ISSUE THREAD

**Issue by hugen1996** [649453932/Chinese-Text-Classification-Pytorch#15]
def __next__(self):
        if self.residue and self.index == self.n_batches:
            batches = self.batches[self.index * self.batch_size: len(self.batches)]
            self.index += 1
            batches = self._to_tensor(batches)
            return batches

        elif self.index > self.n_batches:
            self.index = 0
            raise StopIteration
        else:
            batches = self.batches[self.index * self.batch_size: (self.index + 1) * self.batch_size]
            self.index += 1
            batches = self._to_tensor(batches)
            return batches

这里应该是elif self.index >= self.n_batches吧？？？？

**Comment by XXWong** [comment]
同发现，如果没有等于，当len(batches)整除batch_size的时候就会出问题了

**Comment by 649453932** [comment]
万分感谢！已改正
