### ISSUE TITLE
字转为id有问题

### ISSUE THREAD

**Issue by duguiming111** [649453932/Chinese-Text-Classification-Pytorch#20]
if pad_size:
                    if len(token) < pad_size:
                        token.extend([vocab.get(PAD)] * (pad_size - len(token)))
                    else:
                        token = token[:pad_size]
                        seq_len = pad_size
                # word to id
                for word in token:
                    words_line.append(vocab.get(word, vocab.get(UNK)))
                contents.append((words_line, int(label), seq_len))

这里，vocab.get(word, vocab.get(UNK))得到上面PAD补长的id，这个id不在字典中，最后都成了UNK的id。

**Comment by 649453932** [comment]
构建词表的时候已经把PAD和UNK加进去了：
vocab_dic.update({UNK: len(vocab_dic), PAD: len(vocab_dic) + 1})

**Comment by duguiming111** [comment]
![image](https://user-images.githubusercontent.com/32973161/72508439-9f6e5980-3880-11ea-8b16-66f946e99770.png)
这里的确有问题！大佬，好好检查一下！

**Comment by 649453932** [comment]
看到啦，谢谢大佬！ 晚上回去就改
