### ISSUE TITLE
可能的一个bug

### ISSUE THREAD

**Issue by hans208** [649453932/Chinese-Text-Classification-Pytorch#24]
在utils.py里的load_dataset函数里，第56行
 token.extend([vocab.get(PAD)] * (pad_size - len(token)))
在token里padding，获得的是PAD的id
但下面的代码做了word to id,            
for word in token:
    words_line.append(vocab.get(word, vocab.get(UNK)))
这样的话，因为PAD的id不在词库里，所以PAD都变成了UNK的id了吧，所以个人认为第56行
应该是
 token.extend([PAD] * (pad_size - len(token)))

**Comment by ysgncss** [comment]
帮帮哒，能加个好友么

**Comment by 649453932** [comment]
跪谢！晚上回去改
