### ISSUE TITLE
DPCNN与论文有些不一样

### ISSUE THREAD

**Issue by duguiming111** [649453932/Chinese-Text-Classification-Pytorch#28]
![image](https://user-images.githubusercontent.com/32973161/72675859-7ee31100-3ac5-11ea-890d-a1782de499d9.png)
我看DPCNN代码与论文有些不同，这个是作者做了比较感觉这样更好呢？还是出于其他考虑呢？

**Comment by 649453932** [comment]
大佬你说的是那个残差连接吗，我应该就是单纯的忘记加了。。。
