### ISSUE TITLE
建议增加一个TorchText 作为对比

### ISSUE THREAD

**Issue by 0x0004** [649453932/Chinese-Text-Classification-Pytorch#34]

**Comment by 649453932** [comment]
对比什么

**Comment by 0x0004** [comment]
> 对比什么


模型 | acc 
-- | -- | --
TextCNN | 91.22% 
TextRNN | 91.12% 
TextRNN_Att | 90.90% 
TextRCNN | 91.54% |
FastText | 92.23% 
DPCNN | 91.25%
Transformer | 89.91% 
bert | 94.83%
ERNIE | 94.61% 

在模型效果中对比。

**Comment by 649453932** [comment]
> > 对比什么
> 
> 模型 | acc
> -- | -- | --
> TextCNN | 91.22%
> TextRNN | 91.12%
> TextRNN_Att | 90.90%
> TextRCNN | 91.54% |
> FastText | 92.23%
> DPCNN | 91.25%
> Transformer | 89.91%
> bert | 94.83%
> ERNIE | 94.61%
> 
> 在模型效果中对比。

大哥，torchtext只是个数据处理的工具。。。。

**Comment by 0x0004** [comment]
> > > 对比什么
> > 
> > 
> > 模型 | acc
> > -- | -- | --
> > TextCNN | 91.22%
> > TextRNN | 91.12%
> > TextRNN_Att | 90.90%
> > TextRCNN | 91.54% |
> > FastText | 92.23%
> > DPCNN | 91.25%
> > Transformer | 89.91%
> > bert | 94.83%
> > ERNIE | 94.61%
> > 在模型效果中对比。
> 
> 大哥，torchtext只是个数据处理的工具。。。。

https://pytorch.apachecn.org/docs/1.4/20.html
这个
