### ISSUE TITLE
the while stop condition in DPCNN seems wrong?

### ISSUE THREAD

**Issue by youyou606** [649453932/Chinese-Text-Classification-Pytorch#45]
https://github.com/649453932/Chinese-Text-Classification-Pytorch/blob/6cb26819af7b646275aff8a4693676f2849e67f6/models/DPCNN.py#L69

Should it be ` >= 2`?

**Comment by Yumeka999** [comment]
I think we can use the dpcnn pytorch code of Tencent/NeuralNLP-NeuralClassifier
[dpcnn_pytorch_code_of_tencent](https://github.com/Tencent/NeuralNLP-NeuralClassifier/blob/master/model/classification/dpcnn.py)

**Comment by youyou606** [comment]
Ok, I will see it
