### ISSUE TITLE
关于Assertion `cur_target >= 0 && cur_target

### ISSUE THREAD

**Issue by qiuyuan0929** [649453932/Chinese-Text-Classification-Pytorch#5]
你好~我想请教一下，我替换了自己的数据之后运行FastText时会出现以下报错：
RuntimeError: Assertion `cur_target >= 0 && cur_target < n_classes' failed.  at c:\n\pytorch_1559129895673\work\aten\src\thnn\generic/ClassNLLCriterion.c:93
出现这个报错的原因应该是num.classes和label数量不一致，或者是label并非从0开始。我注意到了这个问题并确认数据label和class.txt无误，但还是持续报错，请问这样该怎么解决呢0 0

**Comment by 649453932** [comment]
没有完整代码我也不知道哪出错了，class.txt就按我的格式放上从0开始的所有label名称，另外label和文本之间是以制表符\t分隔的，你再检查检查吧

**Comment by qiuyuan0929** [comment]
我是以制表符分隔的，class.txt和数据文本都检查过好几遍，都和您的格式一样，实在是不知道为什么会出这个问题……您介意拨冗看看完整的代码吗~如果可以的话我能加一下联系方式来讨论吗？主要是一个论文急用fasttext分类，添麻烦了实在不好意思T T

**Comment by 649453932** [comment]
你的train和test里面除了分割text和label的制表符，是不是文本里面也有制表符，有的话替换成空格。

**Comment by qiuyuan0929** [comment]
去掉制表符之后能运行了，非常感谢帮助！会在论文中把这个repository列为reference的。谢谢~
