### ISSUE TITLE
textRNN模型中LSTM问题

### ISSUE THREAD

**Issue by ghost** [649453932/Chinese-Text-Classification-Pytorch#75]
你好，首先十分感谢你在文本分类模型中的整理，通过学你的代码，受益匪浅。但是在今天在运行代码的时候遇到一个小小的问题，想请教一下，就是在textRNN以及textRNN_Att中，你在使用LSTM的时候输入x的维度为[batch_size, seq_len, embedding]，但是在torch.nn.LSTM源码中是要求输入x的维度是(seq_len, batch, input_size)，想问一下作者这个地方是不是搞反了，或者说这么做是没问题的？

**Comment by oyster-cs** [comment]
`batch_first=True` 了解一下这个参数
