### ISSUE TITLE
TEXT cnn为什么不动啊 也不报错就是不动

### ISSUE THREAD

**Issue by yolo-ai7** [649453932/Chinese-Text-Classification-Pytorch#85]
Loading data...
Vocab size: 4762  
180000it [00:02, 68587.62it/s]
10000it [00:00, 53345.95it/s]
10000it [00:00, 91449.90it/s]
Time usage: 0:00:03
  (convs): ModuleList(
    (0): Conv2d(1, 256, kernel_size=(2, 300), stride=(1, 1))
    (1): Conv2d(1, 256, kernel_size=(3, 300), stride=(1, 1))
    (2): Conv2d(1, 256, kernel_size=(4, 300), stride=(1, 1))
  )
  (dropout): Dropout(p=0.5, inplace=False)
  (fc): Linear(in_features=768, out_features=10, bias=True)
)>
Epoch [1/20]
就不动了 

救救孩子

**Comment by wfnian** [comment]
我也遇到这个问题，请问你解决了吗

**Comment by wfnian** [comment]
#115 https://github.com/649453932/Chinese-Text-Classification-Pytorch/issues/115#issue-2058161911
